import type { CalendarEvent } from "./types";

export const calendarEvents: CalendarEvent[] = [
  {
    id: "lcal-001",
    title: "Hearing: Tariq Mehmood vs. Federation",
    date: "2026-02-18",
    startTime: "10:00",
    endTime: "11:30",
    type: "Hearing",
    caseId: "ltck-001",
    caseTitle: "Tariq Mehmood vs. Federation of Pakistan",
    location: "Lahore High Court, Courtroom 5",
    description: "Main hearing on merits. Bring FBR assessment record and prepared arguments on limitation point.",
  },
  {
    id: "lcal-002",
    title: "Deadline: File Reply - Ayesha Bibi Case",
    date: "2026-02-19",
    startTime: "17:00",
    endTime: "17:00",
    type: "Deadline",
    caseId: "ltck-002",
    caseTitle: "Ayesha Bibi vs. Kamran Shah",
    description: "Last date to file written reply to defendant's application for adjournment. Must be filed before 5 PM.",
  },
  {
    id: "lcal-003",
    title: "Hearing: State vs. Imran Baloch (ATC)",
    date: "2026-02-17",
    startTime: "09:00",
    endTime: "12:00",
    type: "Hearing",
    caseId: "ltck-008",
    caseTitle: "State vs. Imran Baloch",
    location: "Anti-Terrorism Court No. 1, Camp Jail, Lahore",
    description: "Prosecution closing arguments. Prepare cross-examination notes on forensic evidence.",
  },
  {
    id: "lcal-004",
    title: "Meeting: Client Consultation - Malik Zahoor",
    date: "2026-02-15",
    startTime: "14:00",
    endTime: "15:30",
    type: "Meeting",
    caseId: "ltck-006",
    caseTitle: "NAB vs. Malik Zahoor",
    location: "Office",
    description: "Discuss defence strategy for accountability reference. Review bank statements and property documents.",
  },
  {
    id: "lcal-005",
    title: "Reminder: Prepare Brief - Dr. Nadia Ashraf",
    date: "2026-02-16",
    startTime: "09:00",
    endTime: "09:30",
    type: "Reminder",
    caseId: "ltck-009",
    caseTitle: "Dr. Nadia Ashraf vs. PMDC",
    description: "Complete case brief for PMDC writ petition. Focus on Article 18 right to profession arguments.",
  },
  {
    id: "lcal-006",
    title: "Hearing: Shahid Iqbal Bail Application",
    date: "2026-02-19",
    startTime: "11:00",
    endTime: "12:30",
    type: "Hearing",
    caseId: "ltck-015",
    caseTitle: "Shahid Iqbal vs. State",
    location: "Peshawar High Court, Courtroom 3",
    description: "Post-arrest bail hearing. Prosecution to present arguments. Prepare reply on Section 497 new proviso.",
  },
  {
    id: "lcal-007",
    title: "Hearing: Saima Noor Khula Proceedings",
    date: "2026-02-20",
    startTime: "10:30",
    endTime: "11:30",
    type: "Hearing",
    caseId: "ltck-005",
    caseTitle: "Saima Noor vs. Ahmed Raza",
    location: "Family Court, Lahore",
    description: "Hearing on maintenance quantum. Bring salary slips and expense documentation.",
  },
  {
    id: "lcal-008",
    title: "Deadline: Appeal Filing - Zubair Khan",
    date: "2026-02-21",
    startTime: "17:00",
    endTime: "17:00",
    type: "Deadline",
    caseId: "ltck-012",
    caseTitle: "Zubair Khan vs. Commissioner Inland Revenue",
    description: "Last date to file supplementary documents with ATIR. Ensure all annexures are notarized.",
  },
  {
    id: "lcal-009",
    title: "Hearing: Ayesha Bibi Civil Suit",
    date: "2026-02-22",
    startTime: "10:00",
    endTime: "12:00",
    type: "Hearing",
    caseId: "ltck-002",
    caseTitle: "Ayesha Bibi vs. Kamran Shah",
    location: "District Court, Islamabad, Courtroom 12",
    description: "Defence arguments on dowry recovery claim. Order expected.",
  },
  {
    id: "lcal-010",
    title: "Meeting: Team Review - Active Cases",
    date: "2026-02-22",
    startTime: "15:00",
    endTime: "16:30",
    type: "Meeting",
    location: "Office Conference Room",
    description: "Weekly team meeting to review status of all active cases, upcoming deadlines, and task assignments.",
  },
  {
    id: "lcal-011",
    title: "Hearing: Allied Bank vs. Chaudhry Enterprises",
    date: "2026-02-24",
    startTime: "10:00",
    endTime: "11:00",
    type: "Hearing",
    caseId: "ltck-010",
    caseTitle: "Allied Bank vs. Chaudhry Enterprises",
    location: "Banking Court No. 1, Bank Square, Lahore",
    description: "Final arguments from defence side. Prepare written synopsis for court.",
  },
  {
    id: "lcal-012",
    title: "Hearing: Pakistan Textile Mills vs. PRA",
    date: "2026-02-25",
    startTime: "10:30",
    endTime: "12:30",
    type: "Hearing",
    caseId: "ltck-004",
    caseTitle: "Pakistan Textile Mills vs. Punjab Revenue Authority",
    location: "Lahore High Court, Courtroom 8",
    description: "Hearing on merits continuation. AG Punjab to complete arguments. Prepare rejoinder.",
  },
  {
    id: "lcal-013",
    title: "Reminder: Invoice - Chaudhry Enterprises",
    date: "2026-02-23",
    startTime: "10:00",
    endTime: "10:30",
    type: "Reminder",
    description: "Generate and send February invoice to Chaudhry Enterprises. Include hearing attendance and research hours.",
  },
  {
    id: "lcal-014",
    title: "Deadline: File Objections - Rehana Begum Case",
    date: "2026-02-26",
    startTime: "17:00",
    endTime: "17:00",
    type: "Deadline",
    caseId: "ltck-014",
    caseTitle: "Rehana Begum vs. Waqf Board Punjab",
    description: "Last date to file objections to mediator's report before the court.",
  },
  {
    id: "lcal-015",
    title: "Hearing: Lahore Chamber vs. PRA",
    date: "2026-02-27",
    startTime: "11:00",
    endTime: "13:00",
    type: "Hearing",
    caseId: "ltck-013",
    caseTitle: "Lahore Chamber of Commerce vs. PRA",
    location: "Lahore High Court, Courtroom 2",
    description: "Petitioner arguments continuation. Constitutional questions on legislative competence to be addressed.",
  },
  {
    id: "lcal-016",
    title: "Hearing: Hassan Properties vs. KDA",
    date: "2026-02-28",
    startTime: "10:00",
    endTime: "11:30",
    type: "Hearing",
    caseId: "ltck-007",
    caseTitle: "Hassan Properties vs. Karachi Development Authority",
    location: "Sindh High Court, Courtroom 7",
    description: "Arguments on KDA demolition order. Bring approved building plans and NOC copies.",
  },
  {
    id: "lcal-017",
    title: "Meeting: New Client - Property Dispute",
    date: "2026-02-17",
    startTime: "16:00",
    endTime: "17:00",
    type: "Meeting",
    location: "Office",
    description: "Initial consultation with potential new client regarding commercial property dispute in DHA Lahore.",
  },
  {
    id: "lcal-018",
    title: "Reminder: Bar Council Fee Due",
    date: "2026-02-28",
    startTime: "09:00",
    endTime: "09:30",
    type: "Reminder",
    description: "Annual Punjab Bar Council membership renewal fee due by end of February. Submit online or at PBC office.",
  },
  {
    id: "lcal-019",
    title: "Hearing: Muhammad Saleem Rent Case",
    date: "2026-03-02",
    startTime: "10:00",
    endTime: "11:00",
    type: "Hearing",
    caseId: "ltck-011",
    caseTitle: "Muhammad Saleem vs. Bilal Ahmad",
    location: "Rent Tribunal, Rawalpindi",
    description: "Defence evidence date. Tenant to produce witnesses. Prepare cross-examination questions.",
  },
  {
    id: "lcal-020",
    title: "Hearing: Farhan Ali Criminal Appeal",
    date: "2026-03-05",
    startTime: "10:30",
    endTime: "12:00",
    type: "Hearing",
    caseId: "ltck-003",
    caseTitle: "State vs. Farhan Ali",
    location: "Lahore High Court, Courtroom 11",
    description: "Appeal hearing. Arguments on prosecution evidence appreciation and identification parade defects.",
  },
  {
    id: "lcal-021",
    title: "Deadline: Tax Return Filing - Client Portfolio",
    date: "2026-03-01",
    startTime: "23:59",
    endTime: "23:59",
    type: "Deadline",
    description: "Deadline for filing revised income tax returns for three clients: Zubair Khan, Tariq Mehmood, Pakistan Textile Mills.",
  },
  {
    id: "lcal-022",
    title: "Meeting: ATIR Appeal Strategy - Zubair Khan",
    date: "2026-03-04",
    startTime: "11:00",
    endTime: "12:00",
    type: "Meeting",
    caseId: "ltck-012",
    caseTitle: "Zubair Khan vs. Commissioner Inland Revenue",
    location: "Office",
    description: "Review ATIR order and discuss whether to file reference to High Court under Section 133 ITO 2001.",
  },
  {
    id: "lcal-023",
    title: "Hearing: NAB vs. Malik Zahoor",
    date: "2026-03-10",
    startTime: "09:30",
    endTime: "12:00",
    type: "Hearing",
    caseId: "ltck-006",
    caseTitle: "NAB vs. Malik Zahoor",
    location: "Accountability Court No. 2, G-11, Islamabad",
    description: "Defence evidence date. Three character witnesses to be produced. Prepare examination-in-chief.",
  },
  {
    id: "lcal-024",
    title: "Hearing: Rehana Begum vs. Waqf Board",
    date: "2026-03-12",
    startTime: "10:00",
    endTime: "11:00",
    type: "Hearing",
    caseId: "ltck-014",
    caseTitle: "Rehana Begum vs. Waqf Board Punjab",
    location: "District Court, Lahore, Courtroom 9",
    description: "Court to consider mediation report and objections. Possible hearing on merits.",
  },
  {
    id: "lcal-025",
    title: "Hearing: Dr. Nadia Ashraf vs. PMDC",
    date: "2026-03-15",
    startTime: "10:00",
    endTime: "12:00",
    type: "Hearing",
    caseId: "ltck-009",
    caseTitle: "Dr. Nadia Ashraf vs. PMDC",
    location: "Islamabad High Court, Courtroom 4",
    description: "Hearing on merits. PMDC to justify licence cancellation. Prepare rebuttal on procedural fairness grounds.",
  },
];
