import type { TrackedCase } from "./types";

export const trackedCases: TrackedCase[] = [
  {
    id: "ltck-001",
    caseNumber: "W.P. No. 12345/2025",
    title: "Tariq Mehmood vs. Federation of Pakistan",
    court: "Lahore High Court",
    nextDate: "2026-02-18",
    status: "Active",
    clientId: "lcli-001",
    clientName: "Tariq Mehmood",
    events: [
      { id: "evt-001-1", date: "2025-06-15", type: "Filed", description: "Writ petition filed challenging tax assessment order." },
      { id: "evt-001-2", date: "2025-07-20", type: "Hearing", description: "Notice issued to respondents. Adjourned for reply." },
      { id: "evt-001-3", date: "2025-09-10", type: "Arguments", description: "Preliminary arguments heard. Stay order granted." },
      { id: "evt-001-4", date: "2025-11-25", type: "Adjourned", description: "Adjourned due to incomplete record from FBR." },
      { id: "evt-001-5", date: "2026-01-15", type: "Hearing", description: "FBR record received. Arguments resumed." },
    ],
    linkedBriefIds: ["lbrf-001"],
    linkedPetitionIds: ["lpet-001"],
    linkedDocumentIds: ["ldoc-001", "ldoc-002"],
  },
  {
    id: "ltck-002",
    caseNumber: "Civil Suit No. 456/2024",
    title: "Ayesha Bibi vs. Kamran Shah",
    court: "District Court, Islamabad",
    nextDate: "2026-02-22",
    status: "Active",
    clientId: "lcli-002",
    clientName: "Ayesha Bibi",
    events: [
      { id: "evt-002-1", date: "2024-11-05", type: "Filed", description: "Civil suit for recovery of dowry articles filed." },
      { id: "evt-002-2", date: "2024-12-18", type: "Hearing", description: "Written statement filed by defendant." },
      { id: "evt-002-3", date: "2025-03-22", type: "Evidence", description: "Plaintiff evidence recorded. Two witnesses examined." },
      { id: "evt-002-4", date: "2025-07-15", type: "Arguments", description: "Final arguments from plaintiff side completed." },
      { id: "evt-002-5", date: "2025-10-30", type: "Adjourned", description: "Defendant counsel sought adjournment for arguments." },
      { id: "evt-002-6", date: "2026-01-20", type: "Arguments", description: "Defence arguments heard. Case reserved for order." },
    ],
    linkedBriefIds: ["lbrf-002"],
    linkedPetitionIds: ["lpet-002"],
    linkedDocumentIds: ["ldoc-003"],
  },
  {
    id: "ltck-003",
    caseNumber: "Crl. Appeal No. 789/2025",
    title: "State vs. Farhan Ali",
    court: "Lahore High Court",
    nextDate: "2026-03-05",
    status: "Pending",
    clientId: "lcli-003",
    clientName: "Farhan Ali",
    events: [
      { id: "evt-003-1", date: "2025-04-10", type: "Filed", description: "Criminal appeal filed against conviction under Section 302 PPC." },
      { id: "evt-003-2", date: "2025-06-20", type: "Hearing", description: "Record requisitioned from trial court." },
      { id: "evt-003-3", date: "2025-09-15", type: "Hearing", description: "Record received. Bail pending appeal granted." },
    ],
    linkedBriefIds: ["lbrf-003"],
    linkedPetitionIds: [],
    linkedDocumentIds: ["ldoc-004", "ldoc-005"],
  },
  {
    id: "ltck-004",
    caseNumber: "W.P. No. 5678/2025",
    title: "Pakistan Textile Mills vs. Punjab Revenue Authority",
    court: "Lahore High Court",
    nextDate: "2026-02-25",
    status: "Active",
    clientId: "lcli-004",
    clientName: "Pakistan Textile Mills (Pvt.) Ltd.",
    events: [
      { id: "evt-004-1", date: "2025-05-02", type: "Filed", description: "Constitutional petition challenging Punjab sales tax on services." },
      { id: "evt-004-2", date: "2025-06-18", type: "Hearing", description: "Notice issued. Interim relief against recovery granted." },
      { id: "evt-004-3", date: "2025-08-25", type: "Arguments", description: "Arguments on maintainability completed." },
      { id: "evt-004-4", date: "2025-12-10", type: "Hearing", description: "Merits hearing commenced. AG Punjab heard." },
    ],
    linkedBriefIds: ["lbrf-004"],
    linkedPetitionIds: ["lpet-003"],
    linkedDocumentIds: ["ldoc-006"],
  },
  {
    id: "ltck-005",
    caseNumber: "Family Suit No. 234/2025",
    title: "Saima Noor vs. Ahmed Raza",
    court: "Family Court, Lahore",
    nextDate: "2026-02-20",
    status: "Active",
    clientId: "lcli-005",
    clientName: "Saima Noor",
    events: [
      { id: "evt-005-1", date: "2025-03-15", type: "Filed", description: "Suit for dissolution of marriage (Khula) filed." },
      { id: "evt-005-2", date: "2025-04-28", type: "Hearing", description: "Reconciliation proceedings held. No settlement." },
      { id: "evt-005-3", date: "2025-06-12", type: "Evidence", description: "Plaintiff statement on oath recorded." },
      { id: "evt-005-4", date: "2025-09-18", type: "Arguments", description: "Arguments heard on maintenance and dower." },
    ],
    linkedBriefIds: [],
    linkedPetitionIds: ["lpet-004"],
    linkedDocumentIds: ["ldoc-007", "ldoc-008"],
  },
  {
    id: "ltck-006",
    caseNumber: "NAB Ref. No. 12/2024",
    title: "NAB vs. Malik Zahoor",
    court: "Accountability Court No. 2, Islamabad",
    nextDate: "2026-03-10",
    status: "Urgent",
    clientId: "lcli-006",
    clientName: "Malik Zahoor",
    events: [
      { id: "evt-006-1", date: "2024-08-20", type: "Filed", description: "NAB reference filed alleging assets beyond means." },
      { id: "evt-006-2", date: "2024-10-15", type: "Hearing", description: "Charge framed. Accused pleaded not guilty." },
      { id: "evt-006-3", date: "2025-02-28", type: "Evidence", description: "Prosecution evidence commenced. IO examined." },
      { id: "evt-006-4", date: "2025-06-20", type: "Evidence", description: "Bank record witnesses examined." },
      { id: "evt-006-5", date: "2025-10-10", type: "Evidence", description: "Prosecution evidence concluded." },
      { id: "evt-006-6", date: "2026-01-30", type: "Arguments", description: "Defence statement recorded under Section 342 Cr.P.C." },
    ],
    linkedBriefIds: ["lbrf-005"],
    linkedPetitionIds: [],
    linkedDocumentIds: ["ldoc-009", "ldoc-010", "ldoc-011"],
  },
  {
    id: "ltck-007",
    caseNumber: "Civil Rev. No. 900/2025",
    title: "Hassan Properties vs. Karachi Development Authority",
    court: "Sindh High Court",
    nextDate: "2026-02-28",
    status: "Pending",
    clientId: "lcli-007",
    clientName: "Hassan Properties (Pvt.) Ltd.",
    events: [
      { id: "evt-007-1", date: "2025-07-12", type: "Filed", description: "Civil revision filed against KDA demolition order." },
      { id: "evt-007-2", date: "2025-08-25", type: "Hearing", description: "Stay order granted. KDA directed to file reply." },
      { id: "evt-007-3", date: "2025-11-18", type: "Hearing", description: "KDA reply received. Matter adjourned for arguments." },
    ],
    linkedBriefIds: ["lbrf-006"],
    linkedPetitionIds: ["lpet-005"],
    linkedDocumentIds: ["ldoc-012"],
  },
  {
    id: "ltck-008",
    caseNumber: "ATC Case No. 45/2025",
    title: "State vs. Imran Baloch",
    court: "Anti-Terrorism Court No. 1, Lahore",
    nextDate: "2026-02-17",
    status: "Urgent",
    clientId: "lcli-008",
    clientName: "Imran Baloch",
    events: [
      { id: "evt-008-1", date: "2025-01-10", type: "Filed", description: "Challan submitted under Sections 7 & 11-W ATA 1997." },
      { id: "evt-008-2", date: "2025-02-20", type: "Hearing", description: "Charge framed. Accused on judicial remand." },
      { id: "evt-008-3", date: "2025-05-15", type: "Evidence", description: "Prosecution witnesses 1-4 examined." },
      { id: "evt-008-4", date: "2025-08-20", type: "Evidence", description: "Forensic and recovery witnesses examined." },
      { id: "evt-008-5", date: "2025-12-05", type: "Arguments", description: "Defence cross-examination concluded." },
    ],
    linkedBriefIds: ["lbrf-007"],
    linkedPetitionIds: [],
    linkedDocumentIds: ["ldoc-013", "ldoc-014"],
  },
  {
    id: "ltck-009",
    caseNumber: "W.P. No. 3210/2025",
    title: "Dr. Nadia Ashraf vs. PMDC",
    court: "Islamabad High Court",
    nextDate: "2026-03-15",
    status: "Active",
    clientId: "lcli-009",
    clientName: "Dr. Nadia Ashraf",
    events: [
      { id: "evt-009-1", date: "2025-08-05", type: "Filed", description: "Writ petition against cancellation of medical licence." },
      { id: "evt-009-2", date: "2025-09-18", type: "Hearing", description: "Licence suspension stayed. PMDC to file reply." },
      { id: "evt-009-3", date: "2025-12-20", type: "Hearing", description: "PMDC reply received. Hearing on merits fixed." },
    ],
    linkedBriefIds: ["lbrf-008"],
    linkedPetitionIds: ["lpet-006"],
    linkedDocumentIds: ["ldoc-015"],
  },
  {
    id: "ltck-010",
    caseNumber: "Banking Suit No. 678/2024",
    title: "Allied Bank vs. Chaudhry Enterprises",
    court: "Banking Court No. 1, Lahore",
    nextDate: "2026-02-24",
    status: "Active",
    clientId: "lcli-010",
    clientName: "Chaudhry Enterprises",
    events: [
      { id: "evt-010-1", date: "2024-09-10", type: "Filed", description: "Recovery suit filed by Allied Bank for PKR 15 million." },
      { id: "evt-010-2", date: "2024-11-25", type: "Hearing", description: "Leave to defend application filed." },
      { id: "evt-010-3", date: "2025-02-18", type: "Order", description: "Unconditional leave to defend granted." },
      { id: "evt-010-4", date: "2025-06-30", type: "Evidence", description: "Bank officials examined. Account statements exhibited." },
      { id: "evt-010-5", date: "2025-10-22", type: "Arguments", description: "Defence evidence recorded. Both sides heard." },
    ],
    linkedBriefIds: [],
    linkedPetitionIds: [],
    linkedDocumentIds: ["ldoc-016", "ldoc-017"],
  },
  {
    id: "ltck-011",
    caseNumber: "Rent Petition No. 88/2025",
    title: "Muhammad Saleem vs. Bilal Ahmad",
    court: "Rent Tribunal, Rawalpindi",
    nextDate: "2026-03-02",
    status: "Pending",
    clientId: "lcli-011",
    clientName: "Muhammad Saleem",
    events: [
      { id: "evt-011-1", date: "2025-05-20", type: "Filed", description: "Ejectment petition under Punjab Rented Premises Act, 2009." },
      { id: "evt-011-2", date: "2025-07-10", type: "Hearing", description: "Tenant filed written statement. Denied arrears." },
      { id: "evt-011-3", date: "2025-10-15", type: "Evidence", description: "Rent receipts and bank statements exhibited." },
    ],
    linkedBriefIds: [],
    linkedPetitionIds: ["lpet-007"],
    linkedDocumentIds: ["ldoc-018"],
  },
  {
    id: "ltck-012",
    caseNumber: "Appeal No. 1100/2025",
    title: "Zubair Khan vs. Commissioner Inland Revenue",
    court: "Appellate Tribunal Inland Revenue",
    nextDate: "2026-03-08",
    status: "Pending",
    clientId: "lcli-012",
    clientName: "Zubair Khan",
    events: [
      { id: "evt-012-1", date: "2025-06-28", type: "Filed", description: "Appeal against income tax demand for TY 2023." },
      { id: "evt-012-2", date: "2025-08-15", type: "Hearing", description: "FBR directed to produce assessment record." },
      { id: "evt-012-3", date: "2025-11-20", type: "Arguments", description: "Both parties heard on merits. Reserved." },
    ],
    linkedBriefIds: ["lbrf-009"],
    linkedPetitionIds: [],
    linkedDocumentIds: ["ldoc-019"],
  },
  {
    id: "ltck-013",
    caseNumber: "C.P. No. 4500/2025",
    title: "Lahore Chamber of Commerce vs. PRA",
    court: "Lahore High Court",
    nextDate: "2026-02-27",
    status: "Active",
    clientId: "lcli-013",
    clientName: "Lahore Chamber of Commerce",
    events: [
      { id: "evt-013-1", date: "2025-09-01", type: "Filed", description: "Constitutional petition challenging new PRA service tax notification." },
      { id: "evt-013-2", date: "2025-10-10", type: "Order", description: "Interim injunction granted against tax collection." },
      { id: "evt-013-3", date: "2025-12-15", type: "Hearing", description: "AG Punjab arguments heard. Adjourned for petitioner reply." },
      { id: "evt-013-4", date: "2026-01-28", type: "Hearing", description: "Petitioner arguments commenced." },
    ],
    linkedBriefIds: ["lbrf-010"],
    linkedPetitionIds: ["lpet-008"],
    linkedDocumentIds: ["ldoc-020", "ldoc-021"],
  },
  {
    id: "ltck-014",
    caseNumber: "Suit No. 300/2025",
    title: "Rehana Begum vs. Waqf Board Punjab",
    court: "District Court, Lahore",
    nextDate: "2026-03-12",
    status: "Adjourned",
    clientId: "lcli-014",
    clientName: "Rehana Begum",
    events: [
      { id: "evt-014-1", date: "2025-04-22", type: "Filed", description: "Declaratory suit regarding ownership of Waqf property." },
      { id: "evt-014-2", date: "2025-06-30", type: "Hearing", description: "Issues framed by court. Four issues settled." },
      { id: "evt-014-3", date: "2025-09-28", type: "Evidence", description: "Revenue record witnesses examined." },
      { id: "evt-014-4", date: "2025-12-22", type: "Adjourned", description: "Adjourned at joint request for mediation attempt." },
    ],
    linkedBriefIds: [],
    linkedPetitionIds: [],
    linkedDocumentIds: ["ldoc-022"],
  },
  {
    id: "ltck-015",
    caseNumber: "Crl. Misc. No. 2200/2025",
    title: "Shahid Iqbal vs. State",
    court: "Peshawar High Court",
    nextDate: "2026-02-19",
    status: "Urgent",
    clientId: "lcli-015",
    clientName: "Shahid Iqbal",
    events: [
      { id: "evt-015-1", date: "2025-10-05", type: "Filed", description: "Post-arrest bail application under Section 497 Cr.P.C." },
      { id: "evt-015-2", date: "2025-10-20", type: "Hearing", description: "Prosecution opposed. Record requisitioned." },
      { id: "evt-015-3", date: "2025-12-10", type: "Hearing", description: "Record received. Arguments partially heard." },
      { id: "evt-015-4", date: "2026-01-25", type: "Adjourned", description: "Additional prosecutor unavailable. Adjourned." },
    ],
    linkedBriefIds: ["lbrf-011"],
    linkedPetitionIds: ["lpet-009"],
    linkedDocumentIds: ["ldoc-023", "ldoc-024"],
  },
];
