import type { LawyerCase } from "./types";

export const lawyerCases: LawyerCase[] = [
  {
    id: "lcas-001",
    title: "Muhammad Asif v. Federation of Pakistan",
    number: "W.P. No. 1234/2024",
    court: "Lahore High Court",
    citation: "PLD 2024 Lahore 112",
    status: "Active",
    type: "Writ",
    judge: "Justice Shahid Karim",
    filed: "2024-01-15",
    nextHearing: "2025-03-10",
    clientId: "lcli-001",
    clientName: "Muhammad Asif",
    opposingParty: "Federation of Pakistan",
    opposingCounsel: "Deputy Attorney General",
    description:
      "Constitutional petition challenging the legality of tax notices issued under Section 122 of the Income Tax Ordinance, 2001 without providing adequate opportunity of hearing to the petitioner.",
  },
  {
    id: "lcas-002",
    title: "Fatima Begum v. Abdul Rehman",
    number: "Family Suit No. 456/2024",
    court: "Family Court, Lahore",
    citation: "2024 MLD 893",
    status: "Active",
    type: "Family",
    judge: "Judge Samina Akram",
    filed: "2024-02-20",
    nextHearing: "2025-03-18",
    clientId: "lcli-002",
    clientName: "Fatima Begum",
    opposingParty: "Abdul Rehman",
    opposingCounsel: "Adv. Rashid Mehmood",
    description:
      "Suit for dissolution of marriage on grounds of cruelty under Section 2 of the Dissolution of Muslim Marriages Act, 1939 along with recovery of dowry articles and maintenance allowance.",
  },
  {
    id: "lcas-003",
    title: "State v. Imran Khan",
    number: "Criminal Case No. 789/2024",
    court: "Sessions Court, Islamabad",
    citation: "2024 YLR 1567",
    status: "Urgent",
    type: "Criminal Complaint",
    judge: "Judge Aftab Hussain",
    filed: "2024-03-05",
    nextHearing: "2025-02-28",
    clientId: "lcli-003",
    clientName: "Imran Khan",
    opposingParty: "The State",
    opposingCounsel: "Prosecutor Nadeem Butt",
    description:
      "Defence of accused in a criminal case under Sections 420 and 468 PPC for alleged cheating and forgery in a property transaction involving sale deed of agricultural land in Islamabad Capital Territory.",
  },
  {
    id: "lcas-004",
    title: "Allied Textiles Ltd v. National Bank of Pakistan",
    number: "Civil Suit No. 234/2023",
    court: "Islamabad High Court",
    citation: "2024 CLC 445",
    status: "Active",
    type: "Civil Suit",
    judge: "Justice Aamer Farooq",
    filed: "2023-11-12",
    nextHearing: "2025-04-01",
    clientId: "lcli-004",
    clientName: "Allied Textiles Ltd",
    opposingParty: "National Bank of Pakistan",
    opposingCounsel: "Adv. Syed Zafar Ali Shah",
    description:
      "Commercial dispute involving recovery of damages arising from wrongful encashment of bank guarantees amounting to PKR 85 million under the Banking Companies Ordinance, 1962.",
  },
  {
    id: "lcas-005",
    title: "Zainab Bibi v. Revenue Department, Punjab",
    number: "W.P. No. 5678/2024",
    court: "Lahore High Court",
    citation: "PLD 2024 Lahore 298",
    status: "Pending",
    type: "Writ",
    judge: "Justice Ali Baqar Najafi",
    filed: "2024-04-18",
    nextHearing: "2025-05-15",
    clientId: "lcli-005",
    clientName: "Zainab Bibi",
    opposingParty: "Revenue Department, Government of Punjab",
    opposingCounsel: "Advocate General Punjab",
    description:
      "Writ petition for setting aside mutation entries made in the revenue record without notice to the petitioner, who is the legal heir of deceased owner under the Punjab Land Revenue Act, 1967.",
  },
  {
    id: "lcas-006",
    title: "Ahmed Hassan v. Shahid Enterprises",
    number: "Civil Appeal No. 901/2024",
    court: "Supreme Court of Pakistan",
    citation: "2024 SCMR 1123",
    status: "Active",
    type: "Appeal",
    judge: "Justice Qazi Faez Isa",
    filed: "2024-05-10",
    nextHearing: "2025-03-25",
    clientId: "lcli-006",
    clientName: "Ahmed Hassan",
    opposingParty: "Shahid Enterprises (Pvt) Ltd",
    opposingCounsel: "Adv. Makhdoom Ali Khan",
    description:
      "Civil appeal against judgment of Lahore High Court in a partnership dissolution dispute involving distribution of assets worth PKR 200 million under the Partnership Act, 1932.",
  },
  {
    id: "lcas-007",
    title: "Noor Muhammad v. The State",
    number: "Bail Application No. 345/2025",
    court: "Peshawar High Court",
    citation: "2025 YLR 234",
    status: "Urgent",
    type: "Bail",
    judge: "Justice Ijaz Anwar",
    filed: "2025-01-08",
    nextHearing: "2025-02-25",
    clientId: "lcli-007",
    clientName: "Noor Muhammad",
    opposingParty: "The State",
    opposingCounsel: "Additional Prosecutor General KPK",
    description:
      "Post-arrest bail application in a case registered under Sections 302 and 34 PPC at Police Station Hayatabad, Peshawar. Defence based on alibi and lack of direct evidence.",
  },
  {
    id: "lcas-008",
    title: "Karachi Port Trust v. Ocean Shipping Co.",
    number: "Admiralty Suit No. 67/2024",
    court: "High Court of Sindh, Karachi",
    citation: "2024 CLC 889",
    status: "Active",
    type: "Civil Suit",
    judge: "Justice Muhammad Junaid Ghaffar",
    filed: "2024-06-22",
    nextHearing: "2025-04-10",
    clientId: "lcli-008",
    clientName: "Karachi Port Trust",
    opposingParty: "Ocean Shipping Co. Ltd",
    opposingCounsel: "Adv. Faisal Siddiqui",
    description:
      "Admiralty suit for recovery of demurrage charges and port fees amounting to USD 2.3 million for prolonged berthing at Karachi Port under the Admiralty Jurisdiction of High Courts Ordinance, 1980.",
  },
  {
    id: "lcas-009",
    title: "Sadia Parveen v. NADRA",
    number: "W.P. No. 8901/2024",
    court: "Islamabad High Court",
    citation: "2024 CLC 1201",
    status: "Pending",
    type: "Writ",
    judge: "Justice Miangul Hassan Aurangzeb",
    filed: "2024-07-15",
    nextHearing: "2025-05-20",
    clientId: "lcli-009",
    clientName: "Sadia Parveen",
    opposingParty: "National Database and Registration Authority",
    opposingCounsel: "Adv. Arshad Mehmood (NADRA Legal)",
    description:
      "Writ petition challenging NADRA's refusal to update computerized national identity card following marriage, alleging violation of fundamental rights under Articles 4 and 25 of the Constitution.",
  },
  {
    id: "lcas-010",
    title: "Frontier Cement Ltd v. FBR",
    number: "Tax Reference No. 112/2024",
    court: "Supreme Court of Pakistan",
    citation: "2024 SCMR 1890",
    status: "Adjourned",
    type: "Appeal",
    judge: "Justice Mansoor Ali Shah",
    filed: "2024-08-03",
    nextHearing: "2025-06-01",
    clientId: "lcli-010",
    clientName: "Frontier Cement Ltd",
    opposingParty: "Federal Board of Revenue",
    opposingCounsel: "Deputy Attorney General",
    description:
      "Tax reference against order of Appellate Tribunal Inland Revenue regarding disallowance of input tax adjustment of PKR 450 million under Section 8 of the Sales Tax Act, 1990.",
  },
  {
    id: "lcas-011",
    title: "Khalid Mehmood v. WAPDA",
    number: "Civil Suit No. 567/2024",
    court: "District Court, Faisalabad",
    citation: "2024 MLD 1456",
    status: "Active",
    type: "Civil Suit",
    judge: "Judge Muhammad Arshad",
    filed: "2024-03-28",
    nextHearing: "2025-03-15",
    clientId: "lcli-011",
    clientName: "Khalid Mehmood",
    opposingParty: "Water and Power Development Authority",
    opposingCounsel: "WAPDA Legal Division",
    description:
      "Suit for damages against WAPDA for negligence resulting in electrocution injuries to the plaintiff due to exposed high-tension wires near residential area in Faisalabad.",
  },
  {
    id: "lcas-012",
    title: "Bilal Ahmed v. Mst. Rukhsana",
    number: "Guardian Petition No. 78/2024",
    court: "Family Court, Rawalpindi",
    citation: "2024 MLD 2001",
    status: "Active",
    type: "Family",
    judge: "Judge Nasreen Akhtar",
    filed: "2024-09-05",
    nextHearing: "2025-03-22",
    clientId: "lcli-012",
    clientName: "Bilal Ahmed",
    opposingParty: "Mst. Rukhsana Bibi",
    opposingCounsel: "Adv. Saima Farooq",
    description:
      "Petition for custody of minor children under the Guardians and Wards Act, 1890. Father seeking custody on grounds of better welfare and educational opportunities for children aged 8 and 11.",
  },
  {
    id: "lcas-013",
    title: "Pakistan Steel Mills v. Workers Union",
    number: "NIRC Case No. 234/2024",
    court: "National Industrial Relations Commission",
    citation: "2024 PLC (CS) 567",
    status: "Active",
    type: "Miscellaneous",
    judge: "Presiding Officer Tariq Aziz",
    filed: "2024-04-12",
    nextHearing: "2025-04-05",
    clientId: "lcli-004",
    clientName: "Allied Textiles Ltd",
    opposingParty: "Pakistan Steel Workers Union CBA",
    opposingCounsel: "Adv. Muhammad Ilyas Siddiqui",
    description:
      "Industrial dispute regarding termination of 150 workers and demand for reinstatement with back benefits under the Industrial Relations Act, 2012. Management contends retrenchment due to financial crisis.",
  },
  {
    id: "lcas-014",
    title: "Rehman Industries v. Customs Authority",
    number: "Customs Appeal No. 456/2024",
    court: "High Court of Sindh, Karachi",
    citation: "2024 CLC 1678",
    status: "Pending",
    type: "Appeal",
    judge: "Justice Aqeel Ahmed Abbasi",
    filed: "2024-10-01",
    nextHearing: "2025-05-10",
    clientId: "lcli-013",
    clientName: "Rehman Industries",
    opposingParty: "Collector of Customs, Karachi",
    opposingCounsel: "Standing Counsel Customs",
    description:
      "Appeal against order of Customs Appellate Tribunal confirming seizure of imported machinery valued at PKR 120 million on grounds of misdeclaration of HS Code under the Customs Act, 1969.",
  },
  {
    id: "lcas-015",
    title: "Aisha Malik v. Punjab Healthcare Commission",
    number: "W.P. No. 2345/2024",
    court: "Lahore High Court",
    citation: "PLD 2024 Lahore 445",
    status: "Disposed",
    type: "Writ",
    judge: "Justice Abid Aziz Sheikh",
    filed: "2024-02-14",
    nextHearing: "",
    clientId: "lcli-014",
    clientName: "Aisha Malik",
    opposingParty: "Punjab Healthcare Commission",
    opposingCounsel: "Adv. Naveed Shahzad",
    description:
      "Writ petition challenging cancellation of medical practice license under the Punjab Healthcare Commission Act, 2010. Petition was allowed and license restored with conditions.",
  },
  {
    id: "lcas-016",
    title: "Tariq Hussain v. Habib Bank Ltd",
    number: "Banking Case No. 89/2024",
    court: "Banking Court, Lahore",
    citation: "2024 CLC 2100",
    status: "Active",
    type: "Civil Suit",
    judge: "Judge Banking Court-III",
    filed: "2024-05-20",
    nextHearing: "2025-03-28",
    clientId: "lcli-015",
    clientName: "Tariq Hussain",
    opposingParty: "Habib Bank Limited",
    opposingCounsel: "HBL Legal Department",
    description:
      "Suit challenging wrongful classification as willful defaulter by HBL and demanding removal from eCIB list maintained by State Bank of Pakistan. Loan amount disputed: PKR 35 million.",
  },
  {
    id: "lcas-017",
    title: "State v. Sajid Ali",
    number: "Criminal Appeal No. 678/2024",
    court: "Lahore High Court",
    citation: "2024 YLR 2890",
    status: "Active",
    type: "Appeal",
    judge: "Justice Tariq Saleem Sheikh",
    filed: "2024-06-15",
    nextHearing: "2025-04-15",
    clientId: "lcli-003",
    clientName: "Imran Khan",
    opposingParty: "The State",
    opposingCounsel: "Prosecutor General Punjab",
    description:
      "Criminal appeal against conviction under Section 9(c) of the Control of Narcotic Substances Act, 1997 challenging recovery of 5 kg charas on grounds of defective investigation and broken chain of custody.",
  },
  {
    id: "lcas-018",
    title: "Mst. Nasreen v. Board of Revenue",
    number: "W.P. No. 3456/2024",
    court: "Peshawar High Court",
    citation: "PLD 2024 Peshawar 178",
    status: "Reserved",
    type: "Writ",
    judge: "Justice Rooh ul Amin Khan",
    filed: "2024-07-22",
    nextHearing: "2025-03-05",
    clientId: "lcli-005",
    clientName: "Zainab Bibi",
    opposingParty: "Board of Revenue, KPK",
    opposingCounsel: "Additional Advocate General KPK",
    description:
      "Constitutional petition challenging the vires of amendment in KPK Land Revenue Act restricting women's right to inherit agricultural land, invoking Articles 23 and 25 of the Constitution.",
  },
  {
    id: "lcas-019",
    title: "Global Pharma Ltd v. Drug Regulatory Authority",
    number: "W.P. No. 4567/2024",
    court: "Islamabad High Court",
    citation: "2024 CLC 2456",
    status: "Pending",
    type: "Writ",
    judge: "Justice Sardar Ejaz Ishaq Khan",
    filed: "2024-08-10",
    nextHearing: "2025-05-25",
    clientId: "lcli-010",
    clientName: "Frontier Cement Ltd",
    opposingParty: "Drug Regulatory Authority of Pakistan",
    opposingCounsel: "DRAP Legal Wing",
    description:
      "Challenge to suspension of drug manufacturing license without show cause notice under the Drug Regulatory Authority of Pakistan Act, 2012. Seeking interim injunction to continue operations.",
  },
  {
    id: "lcas-020",
    title: "Malik Properties v. CDA",
    number: "Civil Suit No. 890/2024",
    court: "District Court, Islamabad",
    citation: "2024 MLD 3012",
    status: "Active",
    type: "Civil Suit",
    judge: "Judge Asif Iqbal",
    filed: "2024-09-18",
    nextHearing: "2025-04-20",
    clientId: "lcli-006",
    clientName: "Ahmed Hassan",
    opposingParty: "Capital Development Authority",
    opposingCounsel: "CDA Legal Directorate",
    description:
      "Suit for declaration and permanent injunction against CDA's demolition notice for commercial plaza in Blue Area, Islamabad. Challenging validity of notice under CDA Ordinance, 1960.",
  },
  {
    id: "lcas-021",
    title: "Muhammad Usman v. EOBI",
    number: "W.P. No. 5670/2024",
    court: "Lahore High Court",
    citation: "2024 PLC (CS) 890",
    status: "Active",
    type: "Writ",
    judge: "Justice Muzamil Akhtar Shabir",
    filed: "2024-10-05",
    nextHearing: "2025-04-25",
    clientId: "lcli-011",
    clientName: "Khalid Mehmood",
    opposingParty: "Employees Old-Age Benefits Institution",
    opposingCounsel: "EOBI Legal Advisor",
    description:
      "Writ petition for recovery of old-age pension benefits denied on technical grounds of non-registration by employer under the Employees' Old-Age Benefits Act, 1976.",
  },
  {
    id: "lcas-022",
    title: "Naveed & Co. v. Commissioner Inland Revenue",
    number: "Tax Appeal No. 234/2024",
    court: "Appellate Tribunal Inland Revenue, Lahore",
    citation: "2024 PTD 567",
    status: "Adjourned",
    type: "Appeal",
    judge: "Accountant Member Zahid Khan",
    filed: "2024-11-01",
    nextHearing: "2025-06-10",
    clientId: "lcli-001",
    clientName: "Muhammad Asif",
    opposingParty: "Commissioner Inland Revenue, Zone-II, Lahore",
    opposingCounsel: "DR Inland Revenue",
    description:
      "Appeal against assessment order under Section 122(5A) of the Income Tax Ordinance, 2001 for tax year 2022. Disputed addition of unexplained income of PKR 15 million.",
  },
  {
    id: "lcas-023",
    title: "Hina Jabeen v. DHA Lahore",
    number: "Civil Suit No. 123/2025",
    court: "District Court, Lahore",
    citation: "",
    status: "Active",
    type: "Civil Suit",
    judge: "Judge Muhammad Irfan",
    filed: "2025-01-10",
    nextHearing: "2025-03-30",
    clientId: "lcli-002",
    clientName: "Fatima Begum",
    opposingParty: "Defence Housing Authority, Lahore",
    opposingCounsel: "DHA Legal Branch",
    description:
      "Suit for specific performance of agreement to sell plot No. 456-A, Phase VI, DHA Lahore and permanent injunction restraining transfer to any third party.",
  },
  {
    id: "lcas-024",
    title: "State v. Shahzad Ahmad",
    number: "FIR No. 234/2024 - Trial",
    court: "Anti-Terrorism Court, Rawalpindi",
    citation: "2025 YLR 112",
    status: "Urgent",
    type: "Criminal Complaint",
    judge: "Judge ATC-II Rawalpindi",
    filed: "2024-12-01",
    nextHearing: "2025-02-27",
    clientId: "lcli-007",
    clientName: "Noor Muhammad",
    opposingParty: "The State",
    opposingCounsel: "Special Prosecutor ATC",
    description:
      "Trial proceedings under Anti-Terrorism Act, 1997 Section 7. Defence of co-accused on charges of facilitating terrorist financing. Case involves analysis of banking transactions.",
  },
  {
    id: "lcas-025",
    title: "Pakistan Telecom v. PTA",
    number: "W.P. No. 6789/2024",
    court: "Islamabad High Court",
    citation: "2024 CLC 3001",
    status: "Active",
    type: "Writ",
    judge: "Justice Babar Sattar",
    filed: "2024-11-20",
    nextHearing: "2025-04-08",
    clientId: "lcli-008",
    clientName: "Karachi Port Trust",
    opposingParty: "Pakistan Telecommunication Authority",
    opposingCounsel: "PTA Legal Division",
    description:
      "Challenge to PTA's determination on interconnection charges and spectrum allocation under the Pakistan Telecommunication (Re-Organization) Act, 1996. Seeking stay of impugned order.",
  },
  {
    id: "lcas-026",
    title: "Rabia Noor v. Sui Northern Gas",
    number: "Consumer Complaint No. 45/2025",
    court: "District Court, Multan",
    citation: "",
    status: "Pending",
    type: "Civil Suit",
    judge: "Judge Consumer Court Multan",
    filed: "2025-01-20",
    nextHearing: "2025-04-15",
    clientId: "lcli-009",
    clientName: "Sadia Parveen",
    opposingParty: "Sui Northern Gas Pipelines Ltd",
    opposingCounsel: "SNGPL Legal Officer",
    description:
      "Consumer complaint against excessive gas billing and disconnection without notice. Claiming refund of PKR 2.8 million in excess charges and compensation for business losses.",
  },
  {
    id: "lcas-027",
    title: "Review Petition - Asif Tax Case",
    number: "Review Petition No. 56/2025",
    court: "Supreme Court of Pakistan",
    citation: "",
    status: "Pending",
    type: "Review",
    judge: "Justice Yahya Afridi",
    filed: "2025-02-01",
    nextHearing: "2025-06-15",
    clientId: "lcli-001",
    clientName: "Muhammad Asif",
    opposingParty: "Federation of Pakistan",
    opposingCounsel: "Attorney General of Pakistan",
    description:
      "Review petition under Article 188 of the Constitution against dismissal of civil appeal. Seeking review on grounds of error apparent on face of record regarding interpretation of Section 122 Income Tax Ordinance.",
  },
  {
    id: "lcas-028",
    title: "Bashir Trading Co. v. Export Development Fund",
    number: "Civil Misc. No. 789/2024",
    court: "High Court of Sindh, Karachi",
    citation: "2024 CLC 3456",
    status: "Active",
    type: "Miscellaneous",
    judge: "Justice Irfan Saadat Khan",
    filed: "2024-12-15",
    nextHearing: "2025-03-20",
    clientId: "lcli-013",
    clientName: "Rehman Industries",
    opposingParty: "Export Development Fund, Ministry of Commerce",
    opposingCounsel: "Standing Counsel Federal Government",
    description:
      "Miscellaneous application seeking release of export rebate claims of PKR 67 million withheld by EDF under the Export Development Fund Rules. Interim relief of partial release sought.",
  },
];
