import type { CaseFinderResult } from "./types";

export const caseFinderResults: CaseFinderResult[] = [
  {
    id: "cf-001",
    title: "Muhammad Asif v. Federation of Pakistan",
    citation: "PLD 2024 Lahore 112",
    court: "Lahore High Court",
    date: "2024-01-15",
    judge: "Justice Shahid Karim",
    parties: "Muhammad Asif v. Federation of Pakistan",
    summary:
      "Constitutional petition challenging the legality of tax notices issued under Section 122 of the Income Tax Ordinance, 2001. The Court held that the principles of natural justice require that adequate opportunity of hearing must be provided before passing any assessment order. The impugned notices were set aside for violation of the audi alteram partem rule.",
    keyHoldings: [
      "Tax notices under Section 122 must provide adequate opportunity of hearing.",
      "Principles of natural justice are inviolable even in tax proceedings.",
      "The burden lies on the revenue authority to justify departure from the returned income.",
      "Assessment orders passed without hearing are coram non judice.",
    ],
    relatedCaseIds: ["cf-003", "cf-005"],
    statutes: [
      "Income Tax Ordinance, 2001 - Section 122",
      "Constitution of Pakistan - Article 10A",
    ],
  },
  {
    id: "cf-002",
    title: "Khurshid Bibi v. Muhammad Amin",
    citation: "PLD 1967 SC 97",
    court: "Supreme Court of Pakistan",
    date: "1967-03-15",
    judge: "Justice Hamoodur Rahman",
    parties: "Khurshid Bibi v. Muhammad Amin",
    summary:
      "Landmark judgment affirming the wife's right to obtain khula (judicial divorce) without the husband's consent. The Supreme Court held that if the wife is prepared to forgo her dower and other financial benefits, the Court can grant khula. This case established the foundational principle that a Muslim wife has an independent right to seek dissolution of marriage through khula.",
    keyHoldings: [
      "A Muslim wife has the right to seek khula without the husband's consent.",
      "Return of dower (haq mehr) is the consideration for khula, not a precondition.",
      "The Family Court has jurisdiction to grant khula under Islamic law principles.",
      "The right of khula is distinct from the grounds under DMMA 1939.",
    ],
    relatedCaseIds: ["cf-004"],
    statutes: [
      "Dissolution of Muslim Marriages Act, 1939",
      "West Pakistan Family Courts Act, 1964",
    ],
  },
  {
    id: "cf-003",
    title: "Tariq Bashir v. The State",
    citation: "PLD 1995 SC 34",
    court: "Supreme Court of Pakistan",
    date: "1995-02-20",
    judge: "Justice Saleem Akhtar",
    parties: "Tariq Bashir v. The State",
    summary:
      "Comprehensive judgment establishing principles for the grant of bail in non-bailable offences under Section 497 Cr.P.C. The Supreme Court held that bail is the rule and jail is the exception, and that the accused is presumed innocent until proved guilty. The Court laid down detailed guidelines for lower courts to follow when considering bail applications.",
    keyHoldings: [
      "Bail is the rule and jail is the exception.",
      "The accused is presumed innocent until proved guilty beyond reasonable doubt.",
      "Deeper appreciation of evidence is not permissible at the bail stage.",
      "The court must consider the nature of the accusation, severity of punishment, and danger of absconding.",
      "Delay in trial is a valid ground for grant of bail under Section 497(2).",
    ],
    relatedCaseIds: ["cf-001", "cf-007"],
    statutes: [
      "Code of Criminal Procedure, 1898 - Sections 496-498",
      "Constitution of Pakistan - Article 9",
    ],
  },
  {
    id: "cf-004",
    title: "Mst. Naseem Akhtar v. Muhammad Rafiq",
    citation: "2006 MLD 257",
    court: "Lahore High Court",
    date: "2006-05-10",
    judge: "Justice Khilji Arif Hussain",
    parties: "Mst. Naseem Akhtar v. Muhammad Rafiq",
    summary:
      "Important judgment on the Family Court's discretion in determining the amount of dower to be returned in khula proceedings. The Court held that the Family Court is not bound to insist upon return of the full amount of dower and may fix a reasonable amount considering the totality of circumstances, including the husband's conduct and financial position of the wife.",
    keyHoldings: [
      "Family Court has discretion to fix the amount of dower return in khula.",
      "Full dower return is not mandatory; a reasonable amount may be fixed.",
      "Husband's conduct is relevant in determining the return amount.",
      "Financial position of the wife must be considered.",
    ],
    relatedCaseIds: ["cf-002"],
    statutes: [
      "Dissolution of Muslim Marriages Act, 1939",
      "West Pakistan Family Courts Act, 1964 - Section 10",
    ],
  },
  {
    id: "cf-005",
    title: "Sindh High Court Bar Association v. Federation of Pakistan",
    citation: "PLD 2009 SC 879",
    court: "Supreme Court of Pakistan",
    date: "2009-07-31",
    judge: "Justice Iftikhar Muhammad Chaudhry",
    parties: "Sindh High Court Bar Association v. Federation of Pakistan",
    summary:
      "Landmark judgment on the independence of the judiciary as a basic feature of the Constitution. The Supreme Court struck down actions taken during the emergency of November 3, 2007, and established that judicial independence cannot be abrogated even through constitutional amendments. The judgment is considered a watershed moment in Pakistani constitutional law.",
    keyHoldings: [
      "Independence of judiciary is a basic feature of the Constitution.",
      "Constitutional amendments cannot abrogate basic features.",
      "Actions taken during unconstitutional emergency are void ab initio.",
      "The oath of judges under Article 209 is sacrosanct.",
      "Separation of powers is fundamental to constitutional governance.",
    ],
    relatedCaseIds: ["cf-001", "cf-003"],
    statutes: [
      "Constitution of Pakistan - Articles 175-212",
      "Constitution of Pakistan - Article 2A (Objectives Resolution)",
    ],
  },
  {
    id: "cf-006",
    title: "Ali Muhammad v. Muhammad Hussain",
    citation: "2014 SCMR 1240",
    court: "Supreme Court of Pakistan",
    date: "2014-06-15",
    judge: "Justice Anwar Zaheer Jamali",
    parties: "Ali Muhammad v. Muhammad Hussain",
    summary:
      "Authoritative ruling clarifying that mutation in the revenue record does not create or extinguish title to immovable property. The Supreme Court held that mutation is merely a fiscal record maintained for revenue collection purposes and carries only a presumption of correctness under Section 44 of the Punjab Land Revenue Act, which is rebuttable.",
    keyHoldings: [
      "Mutation does not create title; it is a fiscal record.",
      "Mutation entries carry a rebuttable presumption of correctness.",
      "Title can only be transferred through a registered sale deed.",
      "Revenue records are not conclusive proof of ownership.",
    ],
    relatedCaseIds: ["cf-008"],
    statutes: [
      "Punjab Land Revenue Act, 1967 - Section 44",
      "Transfer of Property Act, 1882 - Section 54",
      "Registration Act, 1908",
    ],
  },
  {
    id: "cf-007",
    title: "Asia Bibi v. The State",
    citation: "Criminal Appeal 39-L/2015 (SC)",
    court: "Supreme Court of Pakistan",
    date: "2018-10-31",
    judge: "Justice Saqib Nisar (CJP)",
    parties: "Asia Bibi v. The State",
    summary:
      "Historic acquittal in a blasphemy case. The Supreme Court established higher evidentiary standards for blasphemy prosecutions, emphasizing that the prosecution must prove its case beyond reasonable doubt. The Court found that the testimony of prosecution witnesses was full of contradictions and inconsistencies, and that the accused had been falsely implicated.",
    keyHoldings: [
      "Blasphemy cases require rigorous standard of proof beyond reasonable doubt.",
      "Testimony of interested witnesses must be scrutinized with extreme caution.",
      "False accusation in blasphemy cases is itself a grave offence.",
      "Courts must not be swayed by public pressure in blasphemy trials.",
      "The accused is entitled to fair trial irrespective of the nature of the charge.",
    ],
    relatedCaseIds: ["cf-003"],
    statutes: [
      "Pakistan Penal Code, 1860 - Sections 295-B, 295-C",
      "Constitution of Pakistan - Article 10A",
    ],
  },
  {
    id: "cf-008",
    title: "Muhammad Ismail v. Rukan Din",
    citation: "PLD 2005 SC 293",
    court: "Supreme Court of Pakistan",
    date: "2005-04-20",
    judge: "Justice Javed Iqbal",
    parties: "Muhammad Ismail v. Rukan Din",
    summary:
      "Leading authority on the requirements for specific performance of agreements to sell immovable property. The Court held that the plaintiff must prove continuous readiness and willingness to perform their part of the contract. The mere existence of a written agreement is not sufficient; the plaintiff must demonstrate ability and eagerness to complete the transaction.",
    keyHoldings: [
      "Readiness and willingness must be continuous from the date of agreement.",
      "Financial ability to pay the consideration must be demonstrated.",
      "Time is not of the essence unless expressly stated in the agreement.",
      "The court has discretion to refuse specific performance where it would cause hardship.",
    ],
    relatedCaseIds: ["cf-006"],
    statutes: [
      "Specific Relief Act, 1877 - Sections 12-22",
      "Transfer of Property Act, 1882 - Section 53A",
      "Limitation Act, 1908 - Article 113",
    ],
  },
  {
    id: "cf-009",
    title: "Bytes For All v. Federation of Pakistan",
    citation: "W.P. No. 958/2018 IHC",
    court: "Islamabad High Court",
    date: "2018-09-15",
    judge: "Justice Athar Minallah",
    parties: "Bytes For All Pakistan v. Federation of Pakistan",
    summary:
      "Constitutional challenge to provisions of the Prevention of Electronic Crimes Act (PECA), 2016. The Court emphasized that PECA provisions must be interpreted in light of fundamental rights, particularly freedom of expression under Article 19. Certain broad provisions were read down to prevent abuse and ensure consistency with constitutional protections.",
    keyHoldings: [
      "PECA must be interpreted consistently with fundamental rights.",
      "Freedom of expression under Article 19 includes digital expression.",
      "Overbroad provisions must be read down to prevent abuse.",
      "Blocking of online content requires judicial oversight.",
    ],
    relatedCaseIds: ["cf-007"],
    statutes: [
      "Prevention of Electronic Crimes Act, 2016",
      "Constitution of Pakistan - Article 19",
      "Constitution of Pakistan - Article 19A",
    ],
  },
  {
    id: "cf-010",
    title: "Sughra Begum v. Qaiser Pervez",
    citation: "PLD 2015 SC 177",
    court: "Supreme Court of Pakistan",
    date: "2015-03-25",
    judge: "Justice Asif Saeed Khan Khosa",
    parties: "Sughra Begum v. Qaiser Pervez",
    summary:
      "Authoritative judgment on the scope and application of Section 53A of the Transfer of Property Act, 1882 (doctrine of part performance). The Supreme Court definitively held that Section 53A is a shield, not a sword - it can be used defensively to protect possession but cannot form the basis of an offensive claim for specific performance or title.",
    keyHoldings: [
      "Section 53A is a shield, not a sword.",
      "Part performance protects possession but does not confer title.",
      "Possession must be referable to the contract, not any other arrangement.",
      "An unregistered agreement supported by part performance bars the transferor from disturbing possession.",
    ],
    relatedCaseIds: ["cf-008", "cf-006"],
    statutes: [
      "Transfer of Property Act, 1882 - Section 53A",
      "Registration Act, 1908 - Section 49",
      "Specific Relief Act, 1877",
    ],
  },
];
