import type { Client } from "./types";

export const clients: Client[] = [
  {
    id: "lcli-001",
    name: "Muhammad Asif",
    cnic: "35202-1234567-1",
    phone: "+92-321-4567890",
    email: "m.asif@gmail.com",
    address: "House 45, Block F, Johar Town, Lahore, Punjab",
    caseIds: ["lcas-001", "lcas-022", "lcas-027"],
    lastActivity: "2025-02-10",
    notes:
      "Senior businessman. Tax dispute cases require coordination with his chartered accountant firm M/s Asif & Associates. Prefers evening appointments after 5 PM. Has been a client since 2019.",
  },
  {
    id: "lcli-002",
    name: "Fatima Begum",
    cnic: "35201-9876543-2",
    phone: "+92-300-1234567",
    email: "fatima.begum@yahoo.com",
    address: "Flat 12-B, Al-Noor Apartments, Model Town, Lahore, Punjab",
    caseIds: ["lcas-002", "lcas-023"],
    lastActivity: "2025-02-08",
    notes:
      "Family law client. Going through divorce proceedings. Emotionally sensitive case - requires delicate handling. Has two minor children. Also pursuing property suit regarding DHA plot purchased during marriage.",
  },
  {
    id: "lcli-003",
    name: "Imran Khan",
    cnic: "61101-5678901-3",
    phone: "+92-333-9876543",
    email: "imrankhan.legal@gmail.com",
    address: "House 234, Street 5, Sector F-8/3, Islamabad",
    caseIds: ["lcas-003", "lcas-017"],
    lastActivity: "2025-02-12",
    notes:
      "Multiple criminal cases. Currently on bail in cheating case. Narcotics appeal pending in High Court. Requires frequent jail visits for co-accused coordination. Payment terms: monthly retainer of PKR 200,000.",
  },
  {
    id: "lcli-004",
    name: "Allied Textiles Ltd",
    cnic: "00000-0000000-0",
    phone: "+92-42-35761234",
    email: "legal@alliedtextiles.com.pk",
    address: "Allied Textiles Building, 23-A, Main Boulevard, Gulberg III, Lahore, Punjab",
    caseIds: ["lcas-004", "lcas-013"],
    lastActivity: "2025-02-05",
    notes:
      "Corporate client - large textile manufacturing company. Contact person: Mr. Hamza Ali (Company Secretary). Banking dispute involves complex financial documentation. Also handling their labour dispute at NIRC. Retainer: PKR 500,000/month.",
  },
  {
    id: "lcli-005",
    name: "Zainab Bibi",
    cnic: "17301-4567890-4",
    phone: "+92-345-6789012",
    email: "zainab.bibi@hotmail.com",
    address: "Village Dhoke Hassu, Tehsil Gujar Khan, District Rawalpindi, Punjab",
    caseIds: ["lcas-005", "lcas-018"],
    lastActivity: "2025-01-28",
    notes:
      "Rural client involved in inheritance dispute over 50 kanals of agricultural land. Also challenging KPK amendment on women's inheritance. Pro bono component - partial fee waiver given financial constraints. Transportation from village arranged for hearings.",
  },
  {
    id: "lcli-006",
    name: "Ahmed Hassan",
    cnic: "35202-8901234-5",
    phone: "+92-312-3456789",
    email: "ahmed.hassan@outlook.com",
    address: "78-C, Main Market, Gulberg II, Lahore, Punjab",
    caseIds: ["lcas-006", "lcas-020"],
    lastActivity: "2025-02-11",
    notes:
      "Businessman with partnership dissolution case in Supreme Court and property injunction suit in Islamabad. High-value client. Previously ran Shahid Enterprises as managing partner. Dispute involves Rs. 200 million in assets.",
  },
  {
    id: "lcli-007",
    name: "Noor Muhammad",
    cnic: "16202-3456789-6",
    phone: "+92-334-5678901",
    email: "noor.muhammad@gmail.com",
    address: "House 56, Phase 3, Hayatabad, Peshawar, KPK",
    caseIds: ["lcas-007", "lcas-024"],
    lastActivity: "2025-02-13",
    notes:
      "Criminal defence client. Currently in jail - Central Jail Peshawar. Bail application urgent. Also co-accused in ATC case. Family contact: brother Fazal Muhammad (+92-334-5678902). Fee being paid by family members.",
  },
  {
    id: "lcli-008",
    name: "Karachi Port Trust",
    cnic: "00000-0000000-0",
    phone: "+92-21-32854712",
    email: "legal@kpt.gov.pk",
    address: "KPT Head Office, Eduljee Dinshaw Road, Karachi, Sindh",
    caseIds: ["lcas-008", "lcas-025"],
    lastActivity: "2025-02-06",
    notes:
      "Government body client. Contact person: Director Legal, Mr. Anwar Hussain. Admiralty suit involves international shipping company. Also advising on telecom regulatory matter. All billings through official procurement process - requires pre-approval.",
  },
  {
    id: "lcli-009",
    name: "Sadia Parveen",
    cnic: "61101-2345678-7",
    phone: "+92-301-2345678",
    email: "sadia.parveen@gmail.com",
    address: "House 89, Street 12, Sector G-9/2, Islamabad",
    caseIds: ["lcas-009", "lcas-026"],
    lastActivity: "2025-01-30",
    notes:
      "NADRA CNIC correction case and consumer complaint against SNGPL. The gas billing dispute involves her catering business in Multan. Divides time between Islamabad and Multan. Prefers communication via WhatsApp.",
  },
  {
    id: "lcli-010",
    name: "Frontier Cement Ltd",
    cnic: "00000-0000000-0",
    phone: "+92-51-2876543",
    email: "legal@frontiercement.com.pk",
    address: "Frontier Cement Factory, Hattar Industrial Estate, Haripur, KPK",
    caseIds: ["lcas-010", "lcas-019"],
    lastActivity: "2025-02-03",
    notes:
      "Industrial corporate client. Tax reference in Supreme Court involves substantial revenue implications. Also handling pharma subsidiary's DRAP license issue. Contact: CFO Mr. Sohail Akhtar. Annual retainer agreement.",
  },
  {
    id: "lcli-011",
    name: "Khalid Mehmood",
    cnic: "33100-6789012-8",
    phone: "+92-322-7890123",
    email: "khalid.mehmood@yahoo.com",
    address: "123, Peoples Colony No. 1, Faisalabad, Punjab",
    caseIds: ["lcas-011", "lcas-021"],
    lastActivity: "2025-02-09",
    notes:
      "Personal injury case against WAPDA - client suffered severe burns from exposed wires. Also pursuing EOBI pension claim. Medical documentation extensive. Client is partially disabled - requires home visits for consultations. Fee: contingency basis for WAPDA case.",
  },
  {
    id: "lcli-012",
    name: "Bilal Ahmed",
    cnic: "37405-1234567-9",
    phone: "+92-311-8901234",
    email: "bilal.ahmed@hotmail.com",
    address: "House 67, Satellite Town, Rawalpindi, Punjab",
    caseIds: ["lcas-012"],
    lastActivity: "2025-02-07",
    notes:
      "Child custody case. Father seeking custody of two children aged 8 and 11. Ex-wife has relocated to Rawalpindi. Client is a government servant (Grade 17, Ministry of Interior). Available only on weekends for meetings. Emotional case requiring careful legal strategy.",
  },
  {
    id: "lcli-013",
    name: "Rehman Industries",
    cnic: "00000-0000000-0",
    phone: "+92-21-35678901",
    email: "legal@rehmanindustries.com.pk",
    address: "Plot C-45, SITE Industrial Area, Karachi, Sindh",
    caseIds: ["lcas-014", "lcas-028"],
    lastActivity: "2025-02-04",
    notes:
      "Import/export company. Customs dispute over HS Code classification of industrial machinery. Also pursuing EDF export rebate recovery. Contact: Mr. Danish Rehman (Director). High-value disputes totaling PKR 187 million. Uses Karachi office for meetings.",
  },
  {
    id: "lcli-014",
    name: "Aisha Malik",
    cnic: "35201-5678901-0",
    phone: "+92-303-4567890",
    email: "dr.aisha.malik@gmail.com",
    address: "45-A, Canal Road, Muslim Town, Lahore, Punjab",
    caseIds: ["lcas-015"],
    lastActivity: "2025-01-15",
    notes:
      "Medical doctor whose practice license was cancelled by Punjab Healthcare Commission. Writ petition was successful - license restored with conditions. Case disposed. Final billing pending. May require follow-up if PHC imposes new conditions.",
  },
  {
    id: "lcli-015",
    name: "Tariq Hussain",
    cnic: "35202-9012345-1",
    phone: "+92-320-5678901",
    email: "tariq.hussain@gmail.com",
    address: "Suite 201, Commercial Area, DHA Phase V, Lahore, Punjab",
    caseIds: ["lcas-016"],
    lastActivity: "2025-02-01",
    notes:
      "Banking dispute with HBL. Client was wrongfully classified as willful defaulter affecting his entire business portfolio. Loan amount of PKR 35 million under dispute. Client claims payments were made but not credited. Important documents with bank's receipts filed as evidence.",
  },
];
