import type { ContractReview } from "./types";

export const contractReviews: ContractReview[] = [
  {
    id: "lcr-001",
    title: "Hassan Properties Lease Agreement",
    fileName: "Hassan_Properties_Lease_Agreement_2026.pdf",
    status: "Complete",
    createdAt: "2026-02-10T14:00:00Z",
    overallRisk: "Medium",
    summary:
      "This commercial lease agreement for property in DHA Lahore contains standard rental terms but includes several clauses that could expose the tenant to financial risk. The termination provisions favour the landlord significantly, and the maintenance responsibility allocation is ambiguous.",
    keyTerms: [
      "Lease period: 3 years with option to renew",
      "Monthly rent: PKR 450,000 with 10% annual escalation",
      "Security deposit: 6 months advance rent (PKR 2,700,000)",
      "Permitted use: Commercial office space only",
      "Subletting: Not permitted without landlord consent",
    ],
    obligations: [
      "Tenant must maintain the premises in good condition",
      "Landlord responsible for structural repairs only",
      "Insurance to be maintained by tenant for contents",
      "Quarterly property tax contribution by tenant (25%)",
      "Tenant must provide 90-day written notice for non-renewal",
    ],
    deadlines: [
      "Lease commencement: March 1, 2026",
      "First rent payment: March 1, 2026",
      "Security deposit: Due upon signing",
      "Renewal notice: December 1, 2028",
      "Annual rent review: March 1 each year",
    ],
    redFlags: [
      "Landlord can terminate with only 30 days notice for 'any breach' without cure period",
      "Security deposit forfeiture clause is overly broad",
      "No cap on landlord's recovery of maintenance costs",
      "Dispute resolution clause lacks specificity on arbitration process",
    ],
    clauses: [
      {
        id: "cl-001",
        title: "Termination by Landlord",
        content: "The Landlord may terminate this lease by giving 30 days written notice to the Tenant in the event of any breach of the terms and conditions herein, without providing any opportunity to cure such breach.",
        risk: "High",
        analysis: "This clause is heavily one-sided. Standard practice requires a cure period (typically 15-30 days) before termination. The absence of a cure period means even minor inadvertent breaches could result in immediate eviction. Recommend negotiating a 30-day cure period for non-monetary defaults and 15-day cure for monetary defaults.",
      },
      {
        id: "cl-002",
        title: "Security Deposit & Forfeiture",
        content: "The security deposit of PKR 2,700,000 shall be forfeited in its entirety if the Tenant fails to comply with any of the terms of this agreement, vacates the premises before the expiry of the lease term, or causes any damage beyond normal wear and tear.",
        risk: "High",
        analysis: "The forfeiture provision is overly broad and likely unenforceable under Pakistani contract law. Forfeiture should be limited to actual damages suffered by the landlord. Under Section 74 of the Contract Act, penalty clauses must bear reasonable relation to actual loss. Recommend limiting forfeiture to documented damages only.",
      },
      {
        id: "cl-003",
        title: "Rent Escalation",
        content: "The monthly rent shall be increased by 10% at the commencement of each subsequent year of the lease term. This escalation is non-negotiable and applies regardless of market conditions.",
        risk: "Medium",
        analysis: "While 10% annual escalation is common in Pakistani commercial leases, the non-negotiable nature and disregard for market conditions could be problematic in an economic downturn. Consider negotiating a CPI-linked escalation or a cap of 8-10% with market review option.",
      },
      {
        id: "cl-004",
        title: "Maintenance Responsibilities",
        content: "The Tenant shall be responsible for all maintenance and repairs within the premises. The Landlord shall only be responsible for structural repairs to the building. Any dispute regarding the nature of a repair shall be resolved at the discretion of the Landlord.",
        risk: "Medium",
        analysis: "The clause is ambiguous regarding the boundary between tenant and landlord maintenance responsibilities. The Landlord having sole discretion on categorization creates potential for unfair allocation of major repair costs to the tenant. Recommend defining specific categories of repairs and using an independent surveyor for disputes.",
      },
      {
        id: "cl-005",
        title: "Dispute Resolution",
        content: "Any dispute arising from this agreement shall be resolved through arbitration in Lahore. The arbitrator shall be appointed by mutual consent of the parties.",
        risk: "Low",
        analysis: "The arbitration clause is generally favourable as it avoids lengthy court proceedings. However, it lacks specificity on: appointing authority if parties cannot agree, applicable arbitration rules, timeline for resolution, and cost allocation. Recommend incorporating reference to the Arbitration Act, 1940 and specifying the Lahore Chamber of Commerce as appointing authority.",
      },
      {
        id: "cl-006",
        title: "Permitted Use & Subletting",
        content: "The premises shall be used exclusively for commercial office purposes. Subletting, assignment, or sharing of the premises in any form is strictly prohibited without the prior written consent of the Landlord, which may be withheld at the Landlord's absolute discretion.",
        risk: "Low",
        analysis: "This is a standard restrictive use clause. The absolute discretion on subletting is common but could be negotiated to include a 'not to be unreasonably withheld' qualification. The commercial use restriction is appropriate for the property type.",
      },
    ],
  },
  {
    id: "lcr-002",
    title: "Pakistan Textile Mills Supply Contract",
    fileName: "PTM_Supply_Contract_2026.pdf",
    status: "Complete",
    createdAt: "2026-02-07T10:30:00Z",
    overallRisk: "High",
    summary:
      "This supply contract between Pakistan Textile Mills and a raw materials supplier contains significant risk areas including unlimited liability exposure, unfavourable force majeure provisions, and inadequate intellectual property protections. Immediate legal review recommended before execution.",
    keyTerms: [
      "Contract value: PKR 85,000,000 annually",
      "Duration: 5 years with automatic renewal",
      "Payment terms: Net 60 days from delivery",
      "Minimum order quantity: 500 tons per quarter",
      "Quality standard: ISO 9001:2015 certified",
    ],
    obligations: [
      "Supplier must deliver within 15 business days of order",
      "Buyer must provide quarterly demand forecasts",
      "Buyer responsible for transportation from warehouse",
      "Supplier warrants quality for 12 months from delivery",
      "Both parties must maintain confidentiality for 5 years",
    ],
    deadlines: [
      "Contract effective: April 1, 2026",
      "First delivery: April 15, 2026",
      "Quarterly forecasts: 30 days before quarter start",
      "Annual price review: January 15 each year",
      "Termination notice: 180 days written notice",
    ],
    redFlags: [
      "No limitation on consequential damages for supplier's breach",
      "Force majeure clause does not include pandemics or government actions",
      "Automatic renewal without price adjustment mechanism",
      "Intellectual property ownership clause is ambiguous",
      "No performance bond or guarantee from supplier",
    ],
    clauses: [
      {
        id: "cl2-001",
        title: "Limitation of Liability",
        content: "The Supplier's liability under this agreement shall not exceed the value of the defective goods delivered. The Buyer acknowledges that no claim for consequential, indirect, or special damages shall be made against the Supplier.",
        risk: "High",
        analysis: "This clause eliminates the buyer's ability to recover consequential damages, which in a manufacturing context could be substantial (production downtime, lost orders, contractual penalties). The liability cap at defective goods value is inadequate. Recommend negotiating liability up to the annual contract value and carving out exceptions for negligence and wilful misconduct.",
      },
      {
        id: "cl2-002",
        title: "Force Majeure",
        content: "Neither party shall be liable for failure to perform obligations due to acts of God, war, terrorism, or natural disasters. Force majeure events must be notified within 72 hours.",
        risk: "High",
        analysis: "The force majeure definition is dangerously narrow. It does not include pandemics, government orders, sanctions, supply chain disruptions, or currency controls - all highly relevant in Pakistan's current economic context. Recommend expanding to include epidemic/pandemic, government actions, import/export restrictions, and currency controls.",
      },
      {
        id: "cl2-003",
        title: "Automatic Renewal",
        content: "This agreement shall automatically renew for successive one-year periods unless either party provides 180 days written notice of termination prior to the expiry of the then-current term.",
        risk: "Medium",
        analysis: "Automatic renewal without a price adjustment mechanism locks the buyer into potentially unfavourable pricing for extended periods. In Pakistan's inflationary environment, this could result in above-market payments. Recommend adding CPI-linked price adjustment on renewal or converting to fixed-term with negotiated renewals.",
      },
      {
        id: "cl2-004",
        title: "Quality & Inspection",
        content: "All goods shall conform to the specifications set out in Schedule A. The Buyer shall inspect goods within 7 days of delivery. Failure to reject within this period shall constitute acceptance.",
        risk: "Medium",
        analysis: "The 7-day inspection period is tight for large industrial orders. Latent defects may not be discoverable within this timeframe. Recommend extending to 21 days for apparent defects and 12 months for latent defects, consistent with the warranty period.",
      },
    ],
  },
  {
    id: "lcr-003",
    title: "Fatima Associates LLP Partnership Deed",
    fileName: "Fatima_Associates_LLP_Partnership_Deed.pdf",
    status: "Complete",
    createdAt: "2026-02-03T16:15:00Z",
    overallRisk: "Low",
    summary:
      "This partnership deed for a law firm LLP is well-drafted with standard provisions. Minor improvements recommended in the profit-sharing adjustment mechanism and the non-compete clause duration.",
    keyTerms: [
      "Partnership type: Limited Liability Partnership",
      "Partners: 3 named partners",
      "Capital contribution: PKR 5,000,000 each",
      "Profit sharing: Equal thirds with performance adjustment",
      "Registered under LLP Act, 2017",
    ],
    obligations: [
      "Each partner must contribute minimum 40 billable hours per week",
      "Managing partner to handle administrative duties",
      "Annual audited accounts by approved auditor",
      "Partners must maintain professional indemnity insurance",
      "Quarterly partner meetings mandatory",
    ],
    deadlines: [
      "Partnership commencement: January 1, 2026",
      "Annual accounts: Within 90 days of fiscal year end",
      "Quarterly meetings: First Monday of each quarter",
      "Capital call notice: 30 days minimum",
      "Retirement notice: 6 months written notice",
    ],
    redFlags: [
      "Non-compete clause extends 3 years post-departure (may be unenforceable)",
      "No mechanism for valuing goodwill on partner exit",
    ],
    clauses: [
      {
        id: "cl3-001",
        title: "Non-Compete & Non-Solicitation",
        content: "Upon departure from the partnership, a partner shall not practice law within a 50km radius of any office of the firm for a period of 3 years, nor shall they solicit any client of the firm during this period.",
        risk: "Medium",
        analysis: "While non-compete clauses are common in partnership deeds, the 3-year duration and 50km radius may be considered unreasonable and potentially unenforceable under Pakistani contract law principles. The Pakistan Bar Council rules also restrict such limitations on legal practice. Recommend reducing to 1 year and limiting to active clients only.",
      },
      {
        id: "cl3-002",
        title: "Profit Distribution",
        content: "Profits shall be distributed equally among the partners after deduction of all expenses, taxes, and a 20% reserve fund contribution. Performance adjustments may be made by unanimous consent.",
        risk: "Low",
        analysis: "The equal distribution model is fair and straightforward. The 20% reserve fund is prudent. However, requiring unanimous consent for performance adjustments may create deadlocks. Consider a majority vote mechanism with defined performance metrics.",
      },
      {
        id: "cl3-003",
        title: "Dispute Resolution Among Partners",
        content: "Any dispute among partners shall first be referred to mediation through the Lahore Bar Association. If unresolved within 30 days, the dispute shall proceed to arbitration under the Arbitration Act, 1940.",
        risk: "Low",
        analysis: "This is a well-structured dispute resolution clause with appropriate escalation from mediation to arbitration. The involvement of the Bar Association adds professional context. The 30-day mediation period is reasonable.",
      },
    ],
  },
  {
    id: "lcr-004",
    title: "Karachi Port Trust Service Agreement",
    fileName: "KPT_Service_Agreement_Draft.pdf",
    status: "Analyzing",
    createdAt: "2026-02-14T08:30:00Z",
    overallRisk: "Medium",
    summary: "",
    keyTerms: [],
    obligations: [],
    deadlines: [],
    redFlags: [],
    clauses: [],
  },
];
