import type { LawyerDocument } from "./types";

export const lawyerDocuments: LawyerDocument[] = [
  {
    id: "ldoc-001",
    caseId: "lcas-001",
    clientId: "lcli-001",
    title: "Constitutional Petition under Article 199",
    type: "Petition",
    pages: 18,
    fileSize: "2.4 MB",
    uploadedAt: "2024-01-15",
    category: "Court Filings",
  },
  {
    id: "ldoc-002",
    caseId: "lcas-001",
    clientId: "lcli-001",
    title: "Tax Notices under Section 122 - Annexure Bundle",
    type: "Evidence",
    pages: 45,
    fileSize: "8.7 MB",
    uploadedAt: "2024-01-20",
    category: "Evidence",
  },
  {
    id: "ldoc-003",
    caseId: "lcas-002",
    clientId: "lcli-002",
    title: "Suit for Dissolution of Marriage",
    type: "Petition",
    pages: 12,
    fileSize: "1.8 MB",
    uploadedAt: "2024-02-20",
    category: "Court Filings",
  },
  {
    id: "ldoc-004",
    caseId: "lcas-002",
    clientId: "lcli-002",
    title: "Affidavit of Cruelty - Fatima Begum",
    type: "Affidavit",
    pages: 6,
    fileSize: "890 KB",
    uploadedAt: "2024-02-22",
    category: "Court Filings",
  },
  {
    id: "ldoc-005",
    caseId: "lcas-002",
    clientId: "lcli-002",
    title: "List of Dowry Articles with Photographs",
    type: "Evidence",
    pages: 22,
    fileSize: "15.3 MB",
    uploadedAt: "2024-03-01",
    category: "Evidence",
  },
  {
    id: "ldoc-006",
    caseId: "lcas-003",
    clientId: "lcli-003",
    title: "Written Arguments - Defence in FIR 420/468 PPC",
    type: "Written Arguments",
    pages: 24,
    fileSize: "3.2 MB",
    uploadedAt: "2024-04-10",
    category: "Court Filings",
  },
  {
    id: "ldoc-007",
    caseId: "lcas-004",
    clientId: "lcli-004",
    title: "Bank Guarantee Documents - Allied Textiles",
    type: "Evidence",
    pages: 35,
    fileSize: "6.1 MB",
    uploadedAt: "2023-11-15",
    category: "Evidence",
  },
  {
    id: "ldoc-008",
    caseId: "lcas-004",
    clientId: "lcli-004",
    title: "Agreement of Bank Guarantee Facility",
    type: "Agreement",
    pages: 28,
    fileSize: "4.5 MB",
    uploadedAt: "2023-11-18",
    category: "Contracts",
  },
  {
    id: "ldoc-009",
    caseId: "lcas-005",
    clientId: "lcli-005",
    title: "Writ Petition - Mutation Entries Challenge",
    type: "Petition",
    pages: 15,
    fileSize: "2.1 MB",
    uploadedAt: "2024-04-18",
    category: "Court Filings",
  },
  {
    id: "ldoc-010",
    caseId: "lcas-005",
    clientId: "lcli-005",
    title: "Inheritance Certificate and Fard Malkiat",
    type: "Evidence",
    pages: 8,
    fileSize: "3.4 MB",
    uploadedAt: "2024-04-20",
    category: "Evidence",
  },
  {
    id: "ldoc-011",
    caseId: "lcas-006",
    clientId: "lcli-006",
    title: "Civil Appeal Memorandum - Partnership Dispute",
    type: "Petition",
    pages: 32,
    fileSize: "4.8 MB",
    uploadedAt: "2024-05-10",
    category: "Court Filings",
  },
  {
    id: "ldoc-012",
    caseId: "lcas-006",
    clientId: "lcli-006",
    title: "Partnership Deed - Shahid Enterprises",
    type: "Agreement",
    pages: 14,
    fileSize: "2.0 MB",
    uploadedAt: "2024-05-12",
    category: "Contracts",
  },
  {
    id: "ldoc-013",
    caseId: "lcas-007",
    clientId: "lcli-007",
    title: "Bail Application under Section 497 Cr.P.C.",
    type: "Petition",
    pages: 10,
    fileSize: "1.5 MB",
    uploadedAt: "2025-01-08",
    category: "Court Filings",
  },
  {
    id: "ldoc-014",
    caseId: "lcas-007",
    clientId: "lcli-007",
    title: "Affidavit of Surety - Fazal Muhammad",
    type: "Affidavit",
    pages: 4,
    fileSize: "620 KB",
    uploadedAt: "2025-01-10",
    category: "Court Filings",
  },
  {
    id: "ldoc-015",
    caseId: "lcas-008",
    clientId: "lcli-008",
    title: "Admiralty Suit Plaint - Demurrage Recovery",
    type: "Petition",
    pages: 26,
    fileSize: "3.9 MB",
    uploadedAt: "2024-06-22",
    category: "Court Filings",
  },
  {
    id: "ldoc-016",
    caseId: "lcas-008",
    clientId: "lcli-008",
    title: "Shipping Contract and Bill of Lading",
    type: "Contract",
    pages: 18,
    fileSize: "2.7 MB",
    uploadedAt: "2024-06-25",
    category: "Contracts",
  },
  {
    id: "ldoc-017",
    caseId: "lcas-009",
    clientId: "lcli-009",
    title: "Writ Petition - NADRA CNIC Correction",
    type: "Petition",
    pages: 9,
    fileSize: "1.2 MB",
    uploadedAt: "2024-07-15",
    category: "Court Filings",
  },
  {
    id: "ldoc-018",
    caseId: "lcas-010",
    clientId: "lcli-010",
    title: "Written Arguments - Input Tax Adjustment",
    type: "Written Arguments",
    pages: 38,
    fileSize: "5.6 MB",
    uploadedAt: "2024-09-01",
    category: "Court Filings",
  },
  {
    id: "ldoc-019",
    caseId: "lcas-011",
    clientId: "lcli-011",
    title: "Suit for Damages - Electrocution Injury",
    type: "Petition",
    pages: 14,
    fileSize: "2.0 MB",
    uploadedAt: "2024-03-28",
    category: "Court Filings",
  },
  {
    id: "ldoc-020",
    caseId: "lcas-011",
    clientId: "lcli-011",
    title: "Medical Reports and Hospital Records",
    type: "Evidence",
    pages: 52,
    fileSize: "18.5 MB",
    uploadedAt: "2024-04-05",
    category: "Evidence",
  },
  {
    id: "ldoc-021",
    caseId: "lcas-012",
    clientId: "lcli-012",
    title: "Guardian Petition under Guardians and Wards Act",
    type: "Petition",
    pages: 11,
    fileSize: "1.6 MB",
    uploadedAt: "2024-09-05",
    category: "Court Filings",
  },
  {
    id: "ldoc-022",
    caseId: "lcas-012",
    clientId: "lcli-012",
    title: "Affidavit of Character and Means - Bilal Ahmed",
    type: "Affidavit",
    pages: 5,
    fileSize: "750 KB",
    uploadedAt: "2024-09-08",
    category: "Court Filings",
  },
  {
    id: "ldoc-023",
    caseId: "lcas-014",
    clientId: "lcli-013",
    title: "Customs Appeal Memorandum - HS Code Dispute",
    type: "Petition",
    pages: 20,
    fileSize: "3.0 MB",
    uploadedAt: "2024-10-01",
    category: "Court Filings",
  },
  {
    id: "ldoc-024",
    caseId: "lcas-014",
    clientId: "lcli-013",
    title: "Import Documents and Bill of Entry",
    type: "Evidence",
    pages: 40,
    fileSize: "12.3 MB",
    uploadedAt: "2024-10-05",
    category: "Evidence",
  },
  {
    id: "ldoc-025",
    caseId: "lcas-015",
    clientId: "lcli-014",
    title: "Court Order - License Restoration (Disposed)",
    type: "Court Order",
    pages: 8,
    fileSize: "1.1 MB",
    uploadedAt: "2024-06-10",
    category: "Orders",
  },
  {
    id: "ldoc-026",
    caseId: "lcas-016",
    clientId: "lcli-015",
    title: "Suit Against Willful Defaulter Classification",
    type: "Petition",
    pages: 16,
    fileSize: "2.3 MB",
    uploadedAt: "2024-05-20",
    category: "Court Filings",
  },
  {
    id: "ldoc-027",
    caseId: "lcas-016",
    clientId: "lcli-015",
    title: "Bank Payment Receipts and Ledger Statements",
    type: "Evidence",
    pages: 60,
    fileSize: "22.1 MB",
    uploadedAt: "2024-05-25",
    category: "Evidence",
  },
  {
    id: "ldoc-028",
    caseId: "lcas-003",
    clientId: "lcli-003",
    title: "Power of Attorney - Imran Khan to Counsel",
    type: "Power of Attorney",
    pages: 3,
    fileSize: "450 KB",
    uploadedAt: "2024-03-06",
    category: "Legal Authority",
  },
  {
    id: "ldoc-029",
    caseId: "lcas-020",
    clientId: "lcli-006",
    title: "CDA Demolition Notice and Building Plans",
    type: "Evidence",
    pages: 15,
    fileSize: "9.8 MB",
    uploadedAt: "2024-09-20",
    category: "Evidence",
  },
  {
    id: "ldoc-030",
    caseId: "lcas-023",
    clientId: "lcli-002",
    title: "Agreement to Sell - DHA Plot 456-A Phase VI",
    type: "Agreement",
    pages: 10,
    fileSize: "1.8 MB",
    uploadedAt: "2025-01-10",
    category: "Contracts",
  },
  {
    id: "ldoc-031",
    caseId: "lcas-017",
    clientId: "lcli-003",
    title: "Criminal Appeal - CNSA Challenge",
    type: "Petition",
    pages: 22,
    fileSize: "3.3 MB",
    uploadedAt: "2024-06-15",
    category: "Court Filings",
  },
  {
    id: "ldoc-032",
    caseId: "lcas-013",
    clientId: "lcli-004",
    title: "Notice of Termination to Workers",
    type: "Notice",
    pages: 7,
    fileSize: "980 KB",
    uploadedAt: "2024-04-14",
    category: "Notices",
  },
  {
    id: "ldoc-033",
    caseId: "lcas-018",
    clientId: "lcli-005",
    title: "Written Arguments - Women's Inheritance Rights",
    type: "Written Arguments",
    pages: 30,
    fileSize: "4.2 MB",
    uploadedAt: "2024-08-15",
    category: "Court Filings",
  },
  {
    id: "ldoc-034",
    caseId: "lcas-024",
    clientId: "lcli-007",
    title: "Court Order - Charge Framing ATC",
    type: "Court Order",
    pages: 6,
    fileSize: "850 KB",
    uploadedAt: "2025-01-15",
    category: "Orders",
  },
  {
    id: "ldoc-035",
    caseId: "lcas-028",
    clientId: "lcli-013",
    title: "Legal Notice to Export Development Fund",
    type: "Notice",
    pages: 5,
    fileSize: "720 KB",
    uploadedAt: "2024-12-10",
    category: "Notices",
  },
];
