import type { FileItem } from "./types";

export const fileItems: FileItem[] = [
  // ── 4 Root Folders (parentId: null) ──────────────────────
  {
    id: "lfil-001",
    name: "Cases",
    type: "folder",
    parentId: null,
    date: "2026-02-10",
    children: ["lfil-005", "lfil-006", "lfil-007"],
  },
  {
    id: "lfil-002",
    name: "Clients",
    type: "folder",
    parentId: null,
    date: "2026-02-08",
    children: ["lfil-008", "lfil-009", "lfil-010"],
  },
  {
    id: "lfil-003",
    name: "Templates",
    type: "folder",
    parentId: null,
    date: "2026-01-25",
    children: ["lfil-011", "lfil-012", "lfil-013"],
  },
  {
    id: "lfil-004",
    name: "Personal",
    type: "folder",
    parentId: null,
    date: "2026-02-12",
    children: ["lfil-014", "lfil-015", "lfil-016"],
  },

  // ── 12 Subfolders ────────────────────────────────────────
  // Cases subfolders
  {
    id: "lfil-005",
    name: "Tariq Mehmood vs Federation",
    type: "folder",
    parentId: "lfil-001",
    date: "2026-02-10",
    children: ["lfil-017", "lfil-018", "lfil-019"],
  },
  {
    id: "lfil-006",
    name: "NAB vs Malik Zahoor",
    type: "folder",
    parentId: "lfil-001",
    date: "2026-02-05",
    children: ["lfil-020", "lfil-021", "lfil-022"],
  },
  {
    id: "lfil-007",
    name: "Pakistan Textile Mills vs PRA",
    type: "folder",
    parentId: "lfil-001",
    date: "2026-01-28",
    children: ["lfil-023", "lfil-024", "lfil-025"],
  },

  // Clients subfolders
  {
    id: "lfil-008",
    name: "Tariq Mehmood",
    type: "folder",
    parentId: "lfil-002",
    date: "2026-02-08",
    children: ["lfil-026", "lfil-027"],
  },
  {
    id: "lfil-009",
    name: "Malik Zahoor",
    type: "folder",
    parentId: "lfil-002",
    date: "2026-01-30",
    children: ["lfil-028", "lfil-029"],
  },
  {
    id: "lfil-010",
    name: "Dr. Nadia Ashraf",
    type: "folder",
    parentId: "lfil-002",
    date: "2026-02-05",
    children: ["lfil-030", "lfil-031"],
  },

  // Templates subfolders
  {
    id: "lfil-011",
    name: "Court Forms",
    type: "folder",
    parentId: "lfil-003",
    date: "2026-01-25",
    children: ["lfil-032", "lfil-033"],
  },
  {
    id: "lfil-012",
    name: "Agreements",
    type: "folder",
    parentId: "lfil-003",
    date: "2026-01-20",
    children: ["lfil-034", "lfil-035"],
  },
  {
    id: "lfil-013",
    name: "Notices",
    type: "folder",
    parentId: "lfil-003",
    date: "2026-01-15",
    children: ["lfil-036", "lfil-037"],
  },

  // Personal subfolders
  {
    id: "lfil-014",
    name: "Bar Council",
    type: "folder",
    parentId: "lfil-004",
    date: "2026-02-12",
    children: ["lfil-038", "lfil-039"],
  },
  {
    id: "lfil-015",
    name: "CPD Certificates",
    type: "folder",
    parentId: "lfil-004",
    date: "2026-01-10",
    children: ["lfil-040", "lfil-041"],
  },
  {
    id: "lfil-016",
    name: "Tax Records",
    type: "folder",
    parentId: "lfil-004",
    date: "2026-02-01",
    children: ["lfil-042", "lfil-043"],
  },

  // ── 30 Files ─────────────────────────────────────────────
  // Cases > Tariq Mehmood vs Federation
  {
    id: "lfil-017",
    name: "Writ Petition - Final Draft.pdf",
    type: "file",
    parentId: "lfil-005",
    fileType: "pdf",
    size: "2.4 MB",
    date: "2026-01-15",
    source: "Uploaded",
  },
  {
    id: "lfil-018",
    name: "FBR Assessment Order.pdf",
    type: "file",
    parentId: "lfil-005",
    fileType: "pdf",
    size: "1.8 MB",
    date: "2025-06-10",
    source: "Scanned",
  },
  {
    id: "lfil-019",
    name: "Written Arguments - LHC.docx",
    type: "file",
    parentId: "lfil-005",
    fileType: "docx",
    size: "450 KB",
    date: "2026-02-10",
    source: "AI Generated",
  },

  // Cases > NAB vs Malik Zahoor
  {
    id: "lfil-020",
    name: "NAB Reference Document.pdf",
    type: "file",
    parentId: "lfil-006",
    fileType: "pdf",
    size: "5.2 MB",
    date: "2024-08-20",
    source: "Court Record",
  },
  {
    id: "lfil-021",
    name: "Bank Statement Analysis.xlsx",
    type: "file",
    parentId: "lfil-006",
    fileType: "xlsx",
    size: "890 KB",
    date: "2025-10-05",
    source: "Uploaded",
  },
  {
    id: "lfil-022",
    name: "Defence Statement S.342.docx",
    type: "file",
    parentId: "lfil-006",
    fileType: "docx",
    size: "320 KB",
    date: "2026-01-30",
    source: "AI Generated",
  },

  // Cases > Pakistan Textile Mills vs PRA
  {
    id: "lfil-023",
    name: "Constitutional Petition.pdf",
    type: "file",
    parentId: "lfil-007",
    fileType: "pdf",
    size: "3.1 MB",
    date: "2025-05-02",
    source: "Uploaded",
  },
  {
    id: "lfil-024",
    name: "PRA Tax Notification 2025.pdf",
    type: "file",
    parentId: "lfil-007",
    fileType: "pdf",
    size: "780 KB",
    date: "2025-04-15",
    source: "Downloaded",
  },
  {
    id: "lfil-025",
    name: "AG Punjab Arguments Notes.docx",
    type: "file",
    parentId: "lfil-007",
    fileType: "docx",
    size: "210 KB",
    date: "2025-12-10",
    source: "Uploaded",
  },

  // Clients > Tariq Mehmood
  {
    id: "lfil-026",
    name: "CNIC Copy.pdf",
    type: "file",
    parentId: "lfil-008",
    fileType: "pdf",
    size: "340 KB",
    date: "2025-06-01",
    source: "Scanned",
  },
  {
    id: "lfil-027",
    name: "Engagement Letter - Signed.pdf",
    type: "file",
    parentId: "lfil-008",
    fileType: "pdf",
    size: "520 KB",
    date: "2025-06-05",
    source: "Scanned",
  },

  // Clients > Malik Zahoor
  {
    id: "lfil-028",
    name: "Property Documents Bundle.pdf",
    type: "file",
    parentId: "lfil-009",
    fileType: "pdf",
    size: "12.5 MB",
    date: "2024-08-25",
    source: "Scanned",
  },
  {
    id: "lfil-029",
    name: "Income Tax Returns 2019-2023.pdf",
    type: "file",
    parentId: "lfil-009",
    fileType: "pdf",
    size: "4.8 MB",
    date: "2024-09-10",
    source: "Uploaded",
  },

  // Clients > Dr. Nadia Ashraf
  {
    id: "lfil-030",
    name: "PMDC Registration Certificate.pdf",
    type: "file",
    parentId: "lfil-010",
    fileType: "pdf",
    size: "680 KB",
    date: "2025-08-01",
    source: "Scanned",
  },
  {
    id: "lfil-031",
    name: "Show Cause Notice - PMDC.pdf",
    type: "file",
    parentId: "lfil-010",
    fileType: "pdf",
    size: "420 KB",
    date: "2025-07-15",
    source: "Uploaded",
  },

  // Templates > Court Forms
  {
    id: "lfil-032",
    name: "Writ Petition Template.docx",
    type: "file",
    parentId: "lfil-011",
    fileType: "docx",
    size: "180 KB",
    date: "2025-03-10",
    source: "Template",
  },
  {
    id: "lfil-033",
    name: "Bail Application Template.docx",
    type: "file",
    parentId: "lfil-011",
    fileType: "docx",
    size: "150 KB",
    date: "2025-03-10",
    source: "Template",
  },

  // Templates > Agreements
  {
    id: "lfil-034",
    name: "General Power of Attorney.docx",
    type: "file",
    parentId: "lfil-012",
    fileType: "docx",
    size: "120 KB",
    date: "2025-01-15",
    source: "Template",
  },
  {
    id: "lfil-035",
    name: "Sale Agreement - Property.docx",
    type: "file",
    parentId: "lfil-012",
    fileType: "docx",
    size: "165 KB",
    date: "2025-01-15",
    source: "Template",
  },

  // Templates > Notices
  {
    id: "lfil-036",
    name: "Legal Notice - Recovery.docx",
    type: "file",
    parentId: "lfil-013",
    fileType: "docx",
    size: "95 KB",
    date: "2025-02-20",
    source: "Template",
  },
  {
    id: "lfil-037",
    name: "Cheque Dishonour Notice.docx",
    type: "file",
    parentId: "lfil-013",
    fileType: "docx",
    size: "88 KB",
    date: "2025-02-20",
    source: "Template",
  },

  // Personal > Bar Council
  {
    id: "lfil-038",
    name: "PBC Licence 2025-2026.pdf",
    type: "file",
    parentId: "lfil-014",
    fileType: "pdf",
    size: "1.2 MB",
    date: "2025-07-01",
    source: "Scanned",
  },
  {
    id: "lfil-039",
    name: "LHCBA Membership Card.pdf",
    type: "file",
    parentId: "lfil-014",
    fileType: "pdf",
    size: "450 KB",
    date: "2025-07-05",
    source: "Scanned",
  },

  // Personal > CPD Certificates
  {
    id: "lfil-040",
    name: "CPD Certificate - Tax Law Seminar 2025.pdf",
    type: "file",
    parentId: "lfil-015",
    fileType: "pdf",
    size: "380 KB",
    date: "2025-09-20",
    source: "Downloaded",
  },
  {
    id: "lfil-041",
    name: "CPD Certificate - Criminal Law Workshop.pdf",
    type: "file",
    parentId: "lfil-015",
    fileType: "pdf",
    size: "350 KB",
    date: "2025-11-15",
    source: "Downloaded",
  },

  // Personal > Tax Records
  {
    id: "lfil-042",
    name: "Income Tax Return 2025.pdf",
    type: "file",
    parentId: "lfil-016",
    fileType: "pdf",
    size: "920 KB",
    date: "2025-09-30",
    source: "Uploaded",
  },
  {
    id: "lfil-043",
    name: "Professional Fee Ledger 2025.xlsx",
    type: "file",
    parentId: "lfil-016",
    fileType: "xlsx",
    size: "540 KB",
    date: "2026-01-05",
    source: "Uploaded",
  },

  // Additional files in root case folders (to reach 30 files)
  {
    id: "lfil-044",
    name: "Court Order - Stay Granted.pdf",
    type: "file",
    parentId: "lfil-005",
    fileType: "pdf",
    size: "280 KB",
    date: "2025-09-10",
    source: "Court Record",
  },
  {
    id: "lfil-045",
    name: "Prosecution Evidence List.pdf",
    type: "file",
    parentId: "lfil-006",
    fileType: "pdf",
    size: "1.1 MB",
    date: "2025-02-28",
    source: "Court Record",
  },
  {
    id: "lfil-046",
    name: "Case Synopsis - LHC.docx",
    type: "file",
    parentId: "lfil-007",
    fileType: "docx",
    size: "175 KB",
    date: "2026-01-28",
    source: "AI Generated",
  },
];
